from flask import Flask, render_template, request, jsonify
import subprocess
import os

app = Flask(__name__)

# ==============================
# PAGES
# ==============================

@app.route('/')
def dashboard():
    return render_template('dashboard.html')

@app.route('/extract')
def extract():
    return render_template('extract.html')

@app.route('/report')
def report():
    return render_template('report.html')

# ==============================
# API — this is what buttons call
# ==============================

@app.route('/api/extract', methods=['POST'])
def api_extract():
    # Get the path user selected
    data = request.json
    path = data.get('path', '/sdcard/')

    # Try to pull files from phone using ADB
    try:
        result = subprocess.run(
            ['adb', 'pull', path, './output/'],
            capture_output=True,
            text=True,
            timeout=30
        )
        return jsonify({'message': 'Files extracted successfully! Check output folder.'})

    except FileNotFoundError:
        # ADB not installed — demo mode
        os.makedirs('./output', exist_ok=True)
        with open('./output/demo_file.txt', 'w') as f:
            f.write('This is a demo extracted file.')
        return jsonify({'message': 'Demo mode — ADB not found. A demo file was created in output folder.'})

    except Exception as e:
        return jsonify({'message': 'Error: ' + str(e)})
    
@app.route('/api/report', methods=['POST'])
def api_report():
    import hashlib
    import datetime
    from reportlab.lib.pagesizes import A4
    from reportlab.lib import colors
    from reportlab.lib.units import cm
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.lib.styles import getSampleStyleSheet

    data = request.json
    case_name = data.get('case_name', 'Unknown')
    investigator = data.get('investigator', 'Unknown')

    os.makedirs('./output', exist_ok=True)

    # Collect all files with hashes
    files_data = []
    for filename in os.listdir('./output'):
        full_path = os.path.join('./output', filename)
        if os.path.isfile(full_path):
            # Generate hash for each file
            sha256 = hashlib.sha256()
            with open(full_path, 'rb') as f:
                for chunk in iter(lambda: f.read(4096), b''):
                    sha256.update(chunk)
            files_data.append({
                'name': filename,
                'size': str(round(os.path.getsize(full_path) / 1024, 2)) + ' KB',
                'hash': sha256.hexdigest()
            })

    # Build the PDF
    pdf_path = './output/forensic_report.pdf'
    doc = SimpleDocTemplate(pdf_path, pagesize=A4,
                             rightMargin=2*cm, leftMargin=2*cm,
                             topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    story = []

    # Title
    story.append(Paragraph("🔍 Mobile Forensics Report", styles['Title']))
    story.append(Spacer(1, 12))

    # Case info table
    now = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    info_data = [
        ['Case Name', case_name],
        ['Investigator', investigator],
        ['Report Generated', now],
        ['Total Files', str(len(files_data))],
    ]
    info_table = Table(info_data, colWidths=[5*cm, 10*cm])
    info_table.setStyle(TableStyle([
        ('FONTSIZE', (0,0), (-1,-1), 10),
        ('FONTNAME', (0,0), (0,-1), 'Helvetica-Bold'),
        ('BACKGROUND', (0,0), (0,-1), colors.lightgrey),
        ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
        ('PADDING', (0,0), (-1,-1), 6),
    ]))
    story.append(info_table)
    story.append(Spacer(1, 20))

    # Files table
    story.append(Paragraph("Extracted Files & Hashes", styles['Heading2']))
    story.append(Spacer(1, 8))

    if files_data:
        file_table_data = [['File Name', 'Size', 'SHA-256 Hash']]
        for f in files_data:
            file_table_data.append([f['name'], f['size'], f['hash'][:40] + '...'])

        ft = Table(file_table_data, colWidths=[5*cm, 2.5*cm, 7.5*cm])
        ft.setStyle(TableStyle([
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('FONTSIZE', (0,0), (-1,-1), 8),
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1a1a2e')),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('GRID', (0,0), (-1,-1), 0.3, colors.grey),
            ('PADDING', (0,0), (-1,-1), 5),
        ]))
        story.append(ft)
    else:
        story.append(Paragraph("No files found.", styles['Normal']))

    story.append(Spacer(1, 20))
    story.append(Paragraph("Generated by ForensiKit — Mobile Forensics Tool", styles['Normal']))

    doc.build(story)

    return jsonify({
        'message': 'PDF report generated successfully!',
        'filename': 'forensic_report.pdf'
    })
from flask import send_from_directory

@app.route('/output/<filename>')
def download_file(filename):
    return send_from_directory('./output', filename)


@app.route('/hash')
def hash_page():
    return render_template('hash.html')

@app.route('/api/hash', methods=['POST'])
def api_hash():
    import hashlib

    data = request.json
    filename = data.get('filename', '')

    # Build the full path to the file
    filepath = os.path.join('./output', filename)

    # Check if file exists
    if not os.path.exists(filepath):
        return jsonify({'error': 'File not found!'})

    # Create SHA-256 hash (the fingerprint)
    sha256 = hashlib.sha256()

    with open(filepath, 'rb') as f:
        for chunk in iter(lambda: f.read(4096), b''):
            sha256.update(chunk)

    hash_result = sha256.hexdigest()

    return jsonify({
        'filename': filename,
        'hash': hash_result,
        'message': 'Hash generated successfully!'
    })


@app.route('/api/list-files')
def list_files():
    # List all files in output folder
    files = []
    if os.path.exists('./output'):
        for f in os.listdir('./output'):
            full_path = os.path.join('./output', f)
            if os.path.isfile(full_path):
                size = os.path.getsize(full_path)
                files.append({'name': f, 'size': size})
    return jsonify({'files': files})

@app.route('/recovery')
def recovery_page():
    return render_template('recovery.html')

@app.route('/api/recover')
def api_recover():
    recovered = []

    if not os.path.exists('./output'):
        return jsonify({'files': [], 'count': 0})

    # Walk through every file in output folder
    for filename in os.listdir('./output'):
        full_path = os.path.join('./output', filename)

        if os.path.isfile(full_path):
            reason = None

            # Check 1: hidden file (starts with a dot)
            if filename.startswith('.'):
                reason = 'Hidden file'

            # Check 2: temp or deleted file
            elif filename.endswith('.tmp'):
                reason = 'Temporary file'

            elif filename.endswith('.bak'):
                reason = 'Backup file'

            elif filename.endswith('.deleted'):
                reason = 'Marked as deleted'

            # Check 3: zero byte file (wiped)
            elif os.path.getsize(full_path) == 0:
                reason = 'Empty/wiped file'

            if reason:
                recovered.append({
                    'name': filename,
                    'reason': reason,
                    'size': str(os.path.getsize(full_path)) + ' bytes'
                })

    return jsonify({'files': recovered, 'count': len(recovered)})

from werkzeug.utils import secure_filename

ALLOWED_EXTENSIONS = {'txt', 'pdf', 'png', 'jpg', 'jpeg', 'db', 'csv', 'bak', 'tmp', 'log', 'pptx', 'docx', 'xlsx', 'mp4', 'zip'}

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@app.route('/upload')
def upload_page():
    return render_template('upload.html')

@app.route('/api/upload', methods=['POST'])
def api_upload():
    if 'files' not in request.files:
        return jsonify({'error': 'No files selected!'})

    files = request.files.getlist('files')
    uploaded = []
    skipped = []

    for file in files:
        if file.filename == '':
            continue
        if allowed_file(file.filename):
            filename = secure_filename(file.filename)
            save_path = os.path.join('./output', filename)
            file.save(save_path)
            uploaded.append(filename)
        else:
            skipped.append(file.filename)

    return jsonify({
        'uploaded': uploaded,
        'skipped': skipped,
        'count': len(uploaded),
        'message': f'{len(uploaded)} file(s) uploaded successfully!'
    })

@app.route('/metadata')
def metadata_page():
    return render_template('metadata.html')

@app.route('/api/metadata', methods=['POST'])
def api_metadata():
    from PIL import Image
    from PIL.ExifTags import TAGS, GPSTAGS
    import datetime

    data = request.json
    filename = data.get('filename', '')
    filepath = os.path.join('./output', filename)

    if not os.path.exists(filepath):
        return jsonify({'error': 'File not found!'})

    # Basic file info — works for ALL files
    stat = os.stat(filepath)
    result = {
        'filename': filename,
        'size': str(round(stat.st_size / 1024, 2)) + ' KB',
        'created': str(datetime.datetime.fromtimestamp(stat.st_ctime).strftime('%Y-%m-%d %H:%M:%S')),
        'modified': str(datetime.datetime.fromtimestamp(stat.st_mtime).strftime('%Y-%m-%d %H:%M:%S')),
        'type': filename.rsplit('.', 1)[-1].upper() if '.' in filename else 'Unknown',
        'exif': {},
        'gps': None
    }

    # Try to read EXIF data — only works for images
    try:
        img = Image.open(filepath)
        result['width'] = img.width
        result['height'] = img.height
        result['format'] = img.format

        # Read EXIF tags
        exif_data = img._getexif()
        if exif_data:
            for tag_id, value in exif_data.items():
                tag = TAGS.get(tag_id, tag_id)

                # Skip binary/complex data
                if isinstance(value, (str, int, float)):
                    result['exif'][str(tag)] = str(value)

            # Try to read GPS data
            gps_info = {}
            for tag_id, value in exif_data.items():
                tag = TAGS.get(tag_id, tag_id)
                if tag == 'GPSInfo':
                    for gps_tag_id, gps_value in value.items():
                        gps_tag = GPSTAGS.get(gps_tag_id, gps_tag_id)
                        gps_info[gps_tag] = str(gps_value)
            if gps_info:
                result['gps'] = gps_info

    except Exception:
        result['note'] = 'Not an image or no EXIF data found'

    return jsonify(result)


@app.route('/timeline')
def timeline_page():
    return render_template('timeline.html')

@app.route('/api/timeline')
def api_timeline():
    import datetime
    files = []

    if not os.path.exists('./output'):
        return jsonify({'files': []})

    for filename in os.listdir('./output'):
        full_path = os.path.join('./output', filename)
        if os.path.isfile(full_path):
            stat = os.stat(full_path)
            files.append({
                'name': filename,
                'size': str(round(stat.st_size / 1024, 2)) + ' KB',
                'created': datetime.datetime.fromtimestamp(stat.st_ctime).strftime('%Y-%m-%d %H:%M:%S'),
                'modified': datetime.datetime.fromtimestamp(stat.st_mtime).strftime('%Y-%m-%d %H:%M:%S'),
                'timestamp': stat.st_mtime
            })

    # Sort by modified time — newest first
    files.sort(key=lambda x: x['timestamp'], reverse=True)

    return jsonify({'files': files})


if __name__ == '__main__':
    print("Website is running! Open: http://127.0.0.1:5000")
    app.run(debug=True)

